image:
  file: .gitpod.Dockerfile
tasks:
  - name: Strapi
    init: >
      cd /workspace/elemental-bromine/api &&
      yarn install &&
      yarn seed &&
      gp sync-done strapi
    command: yarn develop
  - name: Vue.js
    init: |
      cd /workspace/elemental-bromine/client &&
      gp sync-await strapi
      yarn install
    command: yarn dev
ports:
  - port: 5173
    onOpen: open-browser
    visibility: public
  - port: 3000
    onOpen: open-browser
    visibility: public